title: Rushi Patel  # your name (or website title) here
logo: "images/Rushi.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Python Connoisseur
  <br><br>
  Data Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/rushi-patel-38ba9a5a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
